spring:
  mvc:
    view:
      suffix: .html
  dubbo:
    consumer:
      check: false
    application:
      id: ldbz-shop-web-cart
      name: ldbz-shop-web-cart
    registry:
      protocol: zookeeper
      address: zookeeper://127.0.0.1:2181
    annotation:
      package: cn.ldbz.cart.controller
      

beetl:
  templates-path: templates/
  config:
      html-tag-flag: true

server:
  port: 8107

# swagger2
swagger2.package: cn.ldbz.cart.controller

# Redis
redisKey:
  prefix:
    # 用户登录信息前缀
    user_session: 'USER_SESSION:'