app:
  id: ldbz-shop-service-notify
apollo:
  meta: http://192.168.136.133:8080

spring:
  dubbo:
    server: true
  datasource:
    druid:
      filter:
        config:
          enabled: true

# Redis 一段时间允许发送几条短信
mobile_number_ceiling: 3

