spring:
  mvc:
    view:
      suffix: .html
  dubbo:
    consumer:
      check: false
    application:
      id: ldbz-shop-web-item
      name: ldbz-shop-web-item
    registry:
      protocol: zookeeper
      address: zookeeper://127.0.0.1:2181
    annotation:
      package: cn.ldbz.item.controller

  thymeleaf:
    content-type: text/html
    mode: LEGACYHTML5
    cache: false

server:
  port: 8103

# swagger2
swagger2.package: cn.ldbz.item.controller